//actionsTypes

//get all 
export const GET_ACTIVITIES_SUCCESS = "GET_ACTIVITIES_SUCCESS"
export const GET_ACTIVITIES_FAIL = "GET_ACTIVITIES_FAIL"
export const GET_ACTIVITIES_LOADING = "GET_ACTIVITIES_LOADING"

//delete 
export const DELETE_ACTIVITIES_SUCCESS = "DELETE_ACTIVITIES_SUCCESS"
export const DELETE_ACTIVITIES_FAIL = "DELETE_ACTIVITIES_FAIL"

//add
export const ADD_ACTIVITIES_SUCCESS = "ADD_ACTIVITIES_SUCCESS"
export const ADD_ACTIVITIES_FAIL = "ADD_ACTIVITIES_FAIL"

//details get one
export const GET_ONE_ACTIVITIE_SUCCESS = "GET_ONE_ACTIVITIE_SUCCESS"
export const GET_ONE_ACTIVITIE_FAIL = "GET_ONE_ACTIVITIE_FAIL"

//update
export const UPDATE_ONE_ACTIVITIES_SUCCESS = "UPDATE_ONE_ACTIVITIES_SUCCESS"
export const UPDATE_ONE_ACTIVITIES_FAIL = "UPDATE_ONE_ACTIVITIES_FAIL"