//signup
export const SIGNUP_USER_FAIL = "SIGNUP_USER_FAIL";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";

//signin
//export const SIGNIN_USER_FAIL = "SIGNIN_USER_FAIL";
//export const SIGNIN_USER_SUCCESS = "SIGNIN_USER_SUCCESS";

//signin user Parent
export const SIGNIN_USER_PARNT_SUCCESS = "SIGNIN_USER_PARNT_SUCCESS";
export const SIGNIN_USER_PARENT_FAIL = "SIGNIN_USER_PARENT_FAIL";

//signin user Educator
export const SIGNIN_USER_EDUCATOR_SUCCESS = "SIGNIN_USER_EDUCATOR_SUCCESS";
export const SIGNIN_USER_EDUCATOR_FAIL = "SIGNIN_USER_EDUCATOR_FAIL";

//get current user: 
export const GET_CURRENT_USER_FAIL = "GET_CURRENT_USER_FAIL";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";

//logout:
export const LOGOUT = "LOGOUT";

//register children
export const REGISTER_CHILDREN_SUCCESS = "REGISTER_CHILDREN_SUCCESS";
export const REGISTER_CHILDREN_FAIL = "REGISTER_CHILDREN_FAIL";